package com.github.aramkhezry.MyStore.Dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.github.aramkhezry.MyStore.Dao.Memory;
import com.github.aramkhezry.MyStore.Dao.SettingApp;

import com.github.aramkhezry.MyStore.Dao.MemoryDao;
import com.github.aramkhezry.MyStore.Dao.SettingAppDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memoryDaoConfig;
    private final DaoConfig settingAppDaoConfig;

    private final MemoryDao memoryDao;
    private final SettingAppDao settingAppDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memoryDaoConfig = daoConfigMap.get(MemoryDao.class).clone();
        memoryDaoConfig.initIdentityScope(type);

        settingAppDaoConfig = daoConfigMap.get(SettingAppDao.class).clone();
        settingAppDaoConfig.initIdentityScope(type);

        memoryDao = new MemoryDao(memoryDaoConfig, this);
        settingAppDao = new SettingAppDao(settingAppDaoConfig, this);

        registerDao(Memory.class, memoryDao);
        registerDao(SettingApp.class, settingAppDao);
    }
    
    public void clear() {
        memoryDaoConfig.getIdentityScope().clear();
        settingAppDaoConfig.getIdentityScope().clear();
    }

    public MemoryDao getMemoryDao() {
        return memoryDao;
    }

    public SettingAppDao getSettingAppDao() {
        return settingAppDao;
    }

}
