package com.github.aramkhezry.MyStore.Dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memoreyDaoConfig;

    private final MemoreyDao memoreyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memoreyDaoConfig = daoConfigMap.get(MemoreyDao.class).clone();
        memoreyDaoConfig.initIdentityScope(type);

        memoreyDao = new MemoreyDao(memoreyDaoConfig, this);

        registerDao(Memorey.class, memoreyDao);
    }
    
    public void clear() {
        memoreyDaoConfig.getIdentityScope().clear();
    }

    public MemoreyDao getMemoreyDao() {
        return memoreyDao;
    }

}
