package com.github.aramkhezry.MyStore.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "MEMOREY".
 */
public class Memorey implements Serializable {

    private Long id;
    private String title;
    private String text;
    private String creatTime;
    private String imageName;
    private String memoryDate;
    private Boolean favorite;
    private String hashtag;

    public Memorey() {
    }

    public Memorey(Long id) {
        this.id = id;
    }

    public Memorey(Long id, String title, String text, String creatTime, String imageName, String memoryDate, Boolean favorite, String hashtag) {
        this.id = id;
        this.title = title;
        this.text = text;
        this.creatTime = creatTime;
        this.imageName = imageName;
        this.memoryDate = memoryDate;
        this.favorite = favorite;
        this.hashtag = hashtag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getCreatTime() {
        return creatTime;
    }

    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime;
    }

    public String getImageName() {
        return imageName;
    }

    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    public String getMemoryDate() {
        return memoryDate;
    }

    public void setMemoryDate(String memoryDate) {
        this.memoryDate = memoryDate;
    }

    public Boolean getFavorite() {
        return favorite;
    }

    public void setFavorite(Boolean favorite) {
        this.favorite = favorite;
    }

    public String getHashtag() {
        return hashtag;
    }

    public void setHashtag(String hashtag) {
        this.hashtag = hashtag;
    }

}
