package com.github.aramkhezry.MyStore.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SETTING_APP".
 */
public class SettingApp {

    private Long id;
    private String password;

    public SettingApp() {
    }

    public SettingApp(Long id) {
        this.id = id;
    }

    public SettingApp(Long id, String password) {
        this.id = id;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
